stages:
  - test
  - deploy

jobs:
  include:
    - name: "Linux (Ubuntu Xenial)"
      stage: test
      os: linux
      dist: bionic
      language: python
      python:
        - "3.6"
        - "3.8"
      cache: pip
    - name: "Mac OSX"
      stage: test
      os: osx
      language: sh
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        - directories:
            - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
    # - name: "Windows"
    #   os: windows
    #   language: sh
    #   env: PATH=$HOME/anaconda/bin/:$PATH
    #   before_install:
    #     - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86.exe
    #     - ./Miniconda3-latest-Windows-x86.exe /S /D=$HOME/anaconda
    #     - python -m pip install --upgrade pip
    #     # - conda install -c conda-forge -r requirements.txt
    #   cache:
    #     - directories:
    #       - $HOME/conda
    - name: "Deploy"
      stage: deploy
      language: python
      os: linux
      script: skip
      deploy:
        provider: pypi
        user: AWehrhahn
        on:
          tags: true
        password:
          secure: uCE8iM+VsNe5s1q/4/rcebhCG2p3rXfwff5cDEWK66YSKzW6TPDabwJ9tvTZPJbsAKXcZua8puy3Su/D8hElkUlGc1gv8W/YBA+E8hdW6cz0H9ZggOjmHVyxZQhgqZZOfq5Vs0YYnbKFV7PcA9NxG6pKWB1SqJqG/oen4vbnCxAybxc2zjqMe1dpC2+VjZeLF1+LGzsNMQ+jfJ8XoaRZ5xiqUDa4p9ohAXSVjxYAF0vnltYQYOpuNZq9jVyRrrYdGngDGdmizCOUI2y6KDVpHtdTeIDOdOCWzva/9iLhtwdjR2D+i7F7ByWcbKRqhyGfrdAwaYeZQy7Cn03WtxfSeVfsFh7uWxf4n8URWJ648VCzKVHO0Nxh7eE6XrekdATQTyNi1CSEmu0E0ATvHwwfCMdSj/HM4b9i5m69pg8Wmn2u+gB28gMAz4a5oGpdxx+cCAMEBmTJojf50PIJTaK1Q6311rP8XhTPH/LVJW4u3RoQ+3/0KICkhjxZ5dByRW7kj59OzJAZ+ZJKAPFq8nBMa3d52cQsaRDzrh6lhx6Ij8IIWGdjGdM57PJhh/PX4jXK8P2i+573Q0S2Ebbot6rj9dOE8Aru46BHBQo6ZzDfBnPA09ppjnrysdsb14pGp10wjZbjDi95df7c7VzUquj7k4JPHN5IMuLS5JitbBzGMGA=

install:
  - pip3 install -r requirements.txt
  - pip3 install -e .
script:
  - pytest