name: pyreduce
channels:
  - defaults
  - astropy
  - anaconda
dependencies:
  - numpy
  - scipy
  - astropy
  - scikit-image
  - python-dateutil
  - wget
  - matplotlib
  - Ipython
  - jupyter
  - pytest
